name: pull_request_target1

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  metadata:
    outputs:
      repository_is_template: ${{ steps.metadata.outputs.repository_is_template }}

    steps:
      - uses: actions/checkout@v3.2.0

      - uses: ahmadnassri/action-metadata@v2.1.2
        id: metadata
